services:
  - type: web
    name: geotracker-api
    env: docker
    repo: https://github.com/Nyxx1928/LinkGuard
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://link-guard-api.onrender.com
      - key: APP_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://link-guard-zero.vercel.app/
      - key: FRONTEND_ORIGINS
        value: https://link-guard-zero.vercel.app/
      - key: SANCTUM_STATEFUL_DOMAINS
        value: link-guard-zero.vercel.app
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: none
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com # from your MySQL provider
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: link-guard-db # from your MySQL provider
      - key: DB_USERNAME
        value: 2KeXfhYXuehz95s.root # from your MySQL provider
      - key: DB_PASSWORD
        sync: false # set in dashboard
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
