import { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import ResultCard from '../components/ResultCard';
import LoadingState from '../components/LoadingState';
import { PageContainer } from '../components/layout';
import MobileNav from '../components/layout/MobileNav';
import CardNav from '../components/ui/CardNav';
import { Button, Card } from '../components/ui';
import { AlertCircle } from 'lucide-react';

/**
 * PublicLookup - Public page for viewing shared lookup results.
 * 
 * This page allows anyone with a UUID to view a lookup result without authentication.
 * It's the destination for shareable links generated by the "Copy link" button.
 * 
 * Features:
 * - Fetches lookup data by UUID from public API
 * - Displays full result using enhanced ResultCard
 * - Professional loading states with LoadingState component
 * - Friendly error handling with clear messages
 * - Provides navigation back to landing page
 * - Uses new design system components for consistency
 * 
 * Requirements: 4.1, 4.3, 6.1, 6.2, 8.1, 8.3, 11.2
 */
const PublicLookup = () => {
  const { uuid } = useParams();
  const navigate = useNavigate();
  const [lookup, setLookup] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [loadingStep, setLoadingStep] = useState(0);

  const fetchLookup = useCallback(async () => {
    setLoading(true);
    setError('');
    setLoadingStep(0);

    try {
      const apiUrl = process.env.REACT_APP_API_URL || 'http://localhost:8000';
      
      // Simulate loading steps for better UX
      setLoadingStep(0);
      await new Promise(resolve => setTimeout(resolve, 300));
      
      setLoadingStep(1);
      const res = await axios.get(`${apiUrl}/api/lookup/${uuid}`);
      
      setLoadingStep(2);
      
      // Transform the data to match ResultCard's expected format
      const transformedData = {
        target: res.data.target,
        type: res.data.type,
        resolved_ip: res.data.resolved_ip,
        geo: res.data.result?.geo || {},
        risk_level: res.data.risk_level,
        uuid: res.data.uuid,
        created_at: res.data.created_at,
        dns_records: res.data.result?.dns_records || [],
      };
      
      setLookup(transformedData);
    } catch (err) {
      console.error('Failed to fetch lookup:', err);
      if (err.response?.status === 404) {
        setError('Lookup not found. The link may be invalid or the lookup may have been deleted.');
      } else if (err.response?.status === 500) {
        setError('Server error occurred. Our team has been notified. Please try again later.');
      } else if (err.code === 'ERR_NETWORK') {
        setError('Network connection failed. Please check your internet connection and try again.');
      } else {
        setError('Failed to load lookup. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  }, [uuid]);

  useEffect(() => {
    fetchLookup();
  }, [fetchLookup]);

  const loadingSteps = [
    'Connecting to server',
    'Fetching lookup data',
    'Preparing results',
  ];

  const cardNavItems = [
    {
      label: 'Platform',
      bgColor: '#0f172a',
      textColor: '#fff',
      links: [
        { label: 'Analyze Links', href: '/analyze', ariaLabel: 'Run a full risk scan instantly' },
        { label: 'Lookup History', href: '/history', ariaLabel: 'Review and label saved results' },
        { label: 'Dashboard', href: '/home', ariaLabel: 'Your security overview at a glance' },
      ],
    },
    {
      label: 'Public Tools',
      bgColor: '#1e293b',
      textColor: '#fff',
      links: [
        { label: 'Public Lookup', href: '/', ariaLabel: 'Shareable checks for any target' },
        { label: 'About LinkGuard', href: '/about', ariaLabel: 'Methodology and data sources' },
      ],
    },
    {
      label: 'Resources',
      bgColor: '#1e293b',
      textColor: '#fff',
      links: [
        { label: 'About', href: '/about', ariaLabel: 'How LinkGuard evaluates risk' },
        { label: 'Component Showcase', href: '/showcase', ariaLabel: 'Design system and UI patterns' },
      ],
    },
  ];

  return (
    <PageContainer>
      {/* Header */}
      <div className="hidden sm:block">
        <CardNav
          logoAlt="LinkGuard"
          items={cardNavItems}
          baseColor="transparent"
          menuColor="#fff"
          buttonBgColor="#111"
          buttonTextColor="#fff"
          ctaLabel="Log In"
          onCtaClick={() => navigate('/login')}
        />
      </div>
      <div className="sm:hidden fixed top-4 right-4 z-50">
        <MobileNav isAuthenticated={false} />
      </div>

      {/* Loading State */}
      {loading && (
        <Card variant="elevated" padding="lg" className="text-center">
          <LoadingState
            message="Loading shared lookup..."
            steps={loadingSteps}
            currentStep={loadingStep}
            size="lg"
          />
        </Card>
      )}

      {/* Error State */}
      {error && !loading && (
        <Card variant="elevated" padding="lg">
          <div className="flex flex-col items-center justify-center text-center">
            <div className="w-16 h-16 bg-risk-danger/10 rounded-full flex items-center justify-center mb-4">
              <AlertCircle className="h-9 w-9 text-risk-danger" />
            </div>
            <h2 className="text-2xl font-bold text-white mb-3">
              Lookup Not Found
            </h2>
            <p className="text-gray-400 mb-6 max-w-md">
              {error}
            </p>
            <div className="flex gap-3">
              <Button
                variant="primary"
                size="md"
                onClick={() => navigate('/')}
              >
                Go to Home Page
              </Button>
              <Button
                variant="secondary"
                size="md"
                onClick={fetchLookup}
              >
                Try Again
              </Button>
            </div>
          </div>
        </Card>
      )}

      {/* Success State - Display Result */}
      {lookup && !loading && !error && (
        <div className="space-y-8">
          <ResultCard result={lookup} showShareLink={true} />
          
          {/* Call to Action */}
          <Card variant="elevated" padding="lg" className="bg-gradient-to-r from-cyan-900/20 to-blue-900/20 border-cyan-700/30">
            <div className="text-center">
              <h2 className="text-2xl font-bold text-white mb-3">
                Want to analyze your own links?
              </h2>
              <p className="text-gray-300 mb-6 max-w-2xl mx-auto">
                Create a free account to save your lookup history, add custom labels, and share results with your team.
              </p>
              <div className="flex justify-center gap-4 flex-wrap">
                <Button
                  variant="primary"
                  size="lg"
                  onClick={() => navigate('/register')}
                >
                  Create Free Account
                </Button>
                <Button
                  variant="secondary"
                  size="lg"
                  onClick={() => navigate('/')}
                >
                  Try It Now
                </Button>
              </div>
            </div>
          </Card>
        </div>
      )}
    </PageContainer>
  );
};

export default PublicLookup;
